import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it, vi } from "vitest";
import type { PluginContext } from "@paperclipai/plugin-sdk";
import * as telegramApi from "../src/telegram-api.js";
import { sendToTelegramTool } from "../src/worker.js";

const token = process.env.TELEGRAM_SMOKE_BOT_TOKEN;
const chatId = process.env.TELEGRAM_SMOKE_CHAT_ID ?? process.env.TELEGRAM_DEFAULT_CHAT_ID;

const runCtx = { companyId: "company-1", agentId: "agent-1" };

type Config = Parameters<typeof sendToTelegramTool>[2];

function createContext(): PluginContext {
  return {
    http: {
      fetch: globalThis.fetch,
    },
    logger: {
      warn: vi.fn(),
      error: vi.fn(),
      info: vi.fn(),
    },
    metrics: {
      write: vi.fn(async () => {}),
    },
    activity: {
      log: vi.fn(),
    },
  } as unknown as PluginContext;
}

function defaultConfig(): Config {
  return {
    defaultChatId: chatId!,
    allowedTelegramChatIds: [],
  };
}

const hasLiveCredentials = typeof token === "string" && token.length > 0 && typeof chatId === "string" && chatId.length > 0;

const describeOrSkip = hasLiveCredentials ? describe : describe.skip;

describeOrSkip("sendToTelegram live smoke", () => {
  it("sends generated markdown file to Telegram as a document", async () => {
    const tmpDir = mkdtempSync(join(tmpdir(), "paperclip-telegram-live-smoke-"));
    const filePath = join(tmpDir, "agent-live-report.md");
    const markdownContent = `# Live smoke\n\nGenerated by TEL-8 smoke test at ${new Date().toISOString()}.`;
    writeFileSync(filePath, markdownContent, "utf8");

    const ctx = createContext();
    const result = await sendToTelegramTool(ctx, token!, defaultConfig(), {
      text: "TEL-8 smoke",
      markdownContent: markdownContent,
      markdownFileName: "agent-live-report.md",
      parseMode: "MarkdownV2",
    }, runCtx);

    expect(result.data).toMatchObject({
      ok: true,
      mode: "document",
      chatId,
      messageId: expect.any(Number),
    });
    expect(result.data.messageId).toBeGreaterThan(0);
  });

  it("sends text-only Telegram message from explicit agent tool path", async () => {
    const ctx = createContext();
    const result = await sendToTelegramTool(ctx, token!, defaultConfig(), {
      text: "TEL-8 text-only live smoke",
    }, runCtx);

    expect(result.data).toMatchObject({
      ok: true,
      mode: "message",
      chatId,
      messageId: expect.any(Number),
    });
    expect(result.data.messageId).toBeGreaterThan(0);
  });

  it("sends markdown-only document with explicit tool path", async () => {
    const ctx = createContext();
    const result = await sendToTelegramTool(ctx, token!, defaultConfig(), {
      markdownContent: "# Live markdown\n\nGenerated by TEL-8 live smoke.",
      markdownFileName: "agent-live-doc.md",
    }, runCtx);

    expect(result.data).toMatchObject({
      ok: true,
      mode: "document",
      chatId,
      messageId: expect.any(Number),
    });
    expect(result.data.messageId).toBeGreaterThan(0);
  });

  it("sends markdown document with caption via explicit tool path", async () => {
    const ctx = createContext();
    const result = await sendToTelegramTool(ctx, token!, defaultConfig(), {
      text: "TEL-8 captioned smoke",
      markdownContent: "# Captioned live smoke\n\nGenerated by TEL-8 live smoke.",
      markdownFileName: "agent-live-caption.md",
    }, runCtx);

    expect(result.data).toMatchObject({
      ok: true,
      mode: "document",
      chatId,
      messageId: expect.any(Number),
    });
    expect(result.data.messageId).toBeGreaterThan(0);
  });
});

describe("sendToTelegram disallowed chat guard (no API call)", () => {
  it("rejects explicit disallowed chat id before Telegram send", async () => {
    const ctx = createContext();
    const spyMessage = vi.spyOn(telegramApi, "sendMessage");
    const spyDocument = vi.spyOn(telegramApi, "sendDocument");

    const result = await sendToTelegramTool(ctx, "raw-test-token", {
      defaultChatId: chatId ?? "telegram-smoke-chat-id",
      allowedTelegramChatIds: [chatId ?? "telegram-smoke-chat-id"],
    }, {
      text: "this must be blocked",
      chatId: "-2002",
    }, runCtx);

    expect(result.data).toEqual({
      ok: false,
      code: "disallowed_chat",
      message: "Telegram chat is not allowed for agent outbound delivery.",
    });
    expect(spyMessage).not.toHaveBeenCalled();
    expect(spyDocument).not.toHaveBeenCalled();
    expect(ctx.metrics.write).not.toHaveBeenCalled();
  });
});
