import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it, vi } from "vitest";
import type { PluginContext } from "@paperclipai/plugin-sdk";
import { sendDocument } from "../src/telegram-api.js";

const token = process.env.TELEGRAM_SMOKE_BOT_TOKEN;
const chatId = process.env.TELEGRAM_SMOKE_CHAT_ID ?? process.env.TELEGRAM_DEFAULT_CHAT_ID;

const hasLiveCredentials = typeof token === "string" && token.length > 0 && typeof chatId === "string" && chatId.length > 0;

const describeOrSkip = hasLiveCredentials ? describe : describe.skip;

describeOrSkip("sendToTelegram live smoke", () => {
  it("sends generated markdown file to Telegram as a document", async () => {
    const tmpDir = mkdtempSync(join(tmpdir(), "paperclip-telegram-live-smoke-"));
    const filePath = join(tmpDir, "agent-live-report.md");
    const markdownContent = `# Live smoke\n\nGenerated by TEL-8 smoke test at ${new Date().toISOString()}.`;
    writeFileSync(filePath, markdownContent, "utf8");

    const ctx = {
      http: {
        fetch: globalThis.fetch,
      },
      logger: {
        warn: vi.fn(),
        error: vi.fn(),
      },
      metrics: {
        write: vi.fn(),
      },
    } as unknown as PluginContext;

    const messageId = await sendDocument(ctx, token!, chatId!, markdownContent, {
      filename: "agent-live-report.md",
      caption: "TEL-8 smoke",
      parseMode: "MarkdownV2",
    });

    expect(typeof messageId).toBe("number");
    expect(messageId).toBeGreaterThan(0);
  });
});
